weights: yolov5s.pt
cfg: C:\Users\Admin\Desktop\GE Healthcare\9 classes latest\yolov5\models\yolov5s.yaml
data: C:\Users\Admin\Desktop\GE Healthcare\9 classes latest\yolov5\data\medeq.yaml
hyp: C:\Users\Admin\Desktop\GE Healthcare\9 classes latest\yolov5\data\hyps\hyp.scratch.yaml
epochs: 100
batch_size: 32
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 24
project: runs\train
name: med_eq9classes_CAT_640
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs\train\med_eq9classes_CAT_640
